from src.FileConfig import Files

CONFIG = [
    Files(
        client="siemens-id enduser",
        dashboard="202508/DB/siemens-id enduser.csv",
        output="202508/Processed/siemens-id enduser.csv",
        carrier="Telkom",
        number1="2150981440",
        number1_rate=780.0,
        number1_rate_type="per_minute",
        number1_chargeable_call_types=['outbound call', 'predictive_dial'],
        number2="2150981440",
        number2_rate=1700.0,
        number2_rate_type="per_minute",
        number2_chargeable_call_types=['incoming call', 'answering machine'],
        rate=0.0,
        rate_type="per_minute",
        s2c=None,
        s2c_rate=0.0,
        s2c_rate_type="per_minute",
        chargeable_call_types=["outbound call", "predictive dialer"],
    ),
    Files(
        client="siemens-id",
        dashboard="202508/DB/siemens-id.csv",
        output="202508/Processed/siemens-id.csv",
        carrier="Telkom",
        number1="2150981440",
        number1_rate=720.0,
        number1_rate_type="per_minute",
        number1_chargeable_call_types=['outbound call', 'predictive_dial'],
        number2="2150981440",
        number2_rate=1500.0,
        number2_rate_type="per_minute",
        number2_chargeable_call_types=['incoming call', 'answering machine'],
        rate=0.0,
        rate_type="per_minute",
        s2c=None,
        s2c_rate=0.0,
        s2c_rate_type="per_minute",
        chargeable_call_types=["outbound call", "predictive dialer"],
    ),
]
